# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  backend:
    image: webapijwt
    build:
      context: .
      dockerfile: WebApiJWT/Dockerfile
    ports:
      - 5000:5235
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  client:
    image: client
    build:
      context: ./web-client-jwt
      dockerfile: Dockerfile
    #volumes:
    #  - ./web-client-jwt:/app   # Mount the local directory into the container
    ports:
      - 5001:5173
  
  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
