# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  backend:
    image: webapijwt
    build:
      context: .
      dockerfile: WebApiJWT/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5000:5235
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
